### ISSUE TITLE
Add "Forgot Password" Feature for Login Page

### ISSUE THREAD

**Issue by FlipEnergy** [ericchu94/chat#9]
Will be added to the BRD first.

**Comment by FlipEnergy** [comment]
@ericchu94 

So I added the feature in the BRD.

As for the email, I can see two options:

1. An email will be sent containing a link to a password reset page 
OR
2. An email will be sent containing a randomly generated temporary password which would replace the user's old password. The user then can use that to log in then automatically direct them to the password change page.

Which do you think is better/easier to implement?

**Comment by ericchu94** [comment]
I'd say the reset is the better solution.

I think this is not a critical issue, so I'd suggest pushing it into module 6

**Comment by FlipEnergy** [comment]
@ericchu94 Done. Please review.

**Comment by ericchu94** [comment]
Looks good

**Comment by FlipEnergy** [comment]
Merged. gh-9 branch deleted.

**Comment by FlipEnergy** [comment]
Issue closed.
